{
    "optimizer": {
        "type": "AdamW",
        "kwargs": {
            "lr": 0.0005,
            "weight_decay": 0.05
        }
    },
    "scheduler": {
        "type": "CosLR",
        "kwargs": {
            "epochs": 300,
            "initial_epochs": 10
        }
    },
    "dataset": {
        "train": {
            "_base_": {
                "NAME": "ScanObjectNN",
                "ROOT": "./Point-MAE/data/ScanObjectNN/main_split"
            },
            "others": {
                "subset": "train",
                "bs": 64
                #"bs": 32
            }
        },
        "val": {
            "_base_": {
                "NAME": "ScanObjectNN",
                "ROOT": "./Point-MAE/data/ScanObjectNN/main_split"
            },
            "others": {
                "subset": "test",
                "bs": 64
            }
        },
        "test": {
            "_base_": {
                "NAME": "ScanObjectNN",
                "ROOT": "./Point-MAE/data/ScanObjectNN/main_split"
            },
            "others": {
                "subset": "test",
                "bs": 64
                #"bs": 32
            }
        }
    },
    "model": {
        "NAME": "PointTransformer",
        "trans_dim": 384,
        "depth": 12,
        "drop_path_rate": 0.1,
        "cls_dim": 15,
        "num_heads": 6,
        "group_size": 32,
        "num_group": 128,
        "encoder_dims": 384
    },
    "npoints": 2048,
    "total_bs": 64,
    "step_per_update": 1,
    "max_epoch": 300,
    "grad_norm_clip": 10
}
