{
    "optimizer": {
        "type": "AdamW",
        "kwargs": {
            "lr": 0.0005,
            "weight_decay": 0.05
        }
    },
    "scheduler": {
        "type": "CosLR",
        "kwargs": {
            "epochs": 300,
            "initial_epochs": 10
        }
    },
    "dataset": {
        "train": {
            "_base_": {
                "NAME": "ScanObjectNN",
                "ROOT": "./Point-MAE/data/ScanObjectNN/main_split",
                "SPLIT": "OBJ-BG",
                "N_POINTS": 2048,
                "subset": "train",
                "bs": 64
            },
            "others": {
                "subset": "train",
                "bs": 64
            }
        },
        "val": {
            "_base_": {
                "NAME": "ScanObjectNN",
                "ROOT": "./Point-MAE/data/ScanObjectNN/main_split",
                "SPLIT": "OBJ-BG",
                "N_POINTS": 2048,
                "subset": "test",
                "bs": 64
            },
            "others": {
                "subset": "test",
                "bs": 64
            }
        },
        "test": {
            "_base_": {
                "NAME": "ScanObjectNN",
                "ROOT": "./Point-MAE/data/ScanObjectNN/main_split",
                "SPLIT": "OBJ-BG",
                "N_POINTS": 2048
            },
            "others": {
                "subset": "test",
                "bs": 64
            }
        }
    },
    "model": {
        "NAME": "Point_M2AE_ScanObjectNN",
        "group_sizes": [
            32,
            16,
            16
        ],
        "num_groups": [
            512,
            256,
            64
        ],
        "encoder_depths": [
            5,
            5,
            5
        ],
        "encoder_dims": [
            96,
            192,
            384
        ],
        "local_radius": [
            0.32,
            0.64,
            1.28
        ],
        "drop_path_rate": 0.1,
        "num_heads": 6
    },
    "npoints": 2048,
    "total_bs": 64,
    "step_per_update": 1,
    "max_epoch": 300,
    "grad_norm_clip": 10
}
