{
    "optimizer": {
        "type": "AdamW",
        "kwargs": {
            "lr": 0.001,
            "weight_decay": 0.05
        }
    },
    "scheduler": {
        "type": "CosLR",
        "kwargs": {
            "epochs": 400,
            "initial_epochs": 10
        }
    },
    "dataset": {
        "train": {
            "_base_": {
                "NAME": "ShapeNet",
                "DATA_PATH": "./Point-M2AE/data/ShapeNet55-34/ShapeNet-55",
                "N_POINTS": 8192,
                "PC_PATH": "./Point-M2AE/data/ShapeNet55-34/shapenet_pc"
            },
            "others": {
                "subset": "train",
                "npoints": 2048,
                "bs": 128
            }
        },
        "val": {
            "_base_": {
                "NAME": "ShapeNet",
                "DATA_PATH": "./Point-M2AE/data/ShapeNet55-34/ShapeNet-55",
                "N_POINTS": 8192,
                "PC_PATH": "./Point-M2AE/data/ShapeNet55-34/shapenet_pc"
            },
            "others": {
                "subset": "test",
                "npoints": 2048,
                "bs": 128
            }
        },
        "test": {
            "_base_": {
                "NAME": "ShapeNet",
                "DATA_PATH": "./Point-M2AE/data/ShapeNet55-34/ShapeNet-55",
                "N_POINTS": 8192,
                "PC_PATH": "./Point-M2AE/data/ShapeNet55-34/shapenet_pc"
            },
            "others": {
                "subset": "test",
                "npoints": 2048,
                "bs": 128
            }
        }
    },
    "model": {
        "NAME": "Point_M2AE",
        "mask_ratio": 0.8,
        "group_sizes": [
            16,
            8,
            8
        ],
        "num_groups": [
            512,
            256,
            64
        ],
        "encoder_depths": [
            5,
            5,
            5
        ],
        "encoder_dims": [
            96,
            192,
            384
        ],
        "local_radius": [
            0.32,
            0.64,
            1.28
        ],
        "decoder_depths": [
            1,
            1
        ],
        "decoder_dims": [
            384,
            192
        ],
        "decoder_up_blocks": [
            1,
            1
        ],
        "drop_path_rate": 0.1,
        "num_heads": 6
    },
    "npoints": 2048,
    "total_bs": 128,
    "step_per_update": 1,
    "max_epoch": 300
}
