{
    "optimizer": {
        "type": "AdamW",
        "kwargs": {
            "lr": 0.001,
            "weight_decay": 0.05
        }
    },
    "scheduler": {
        "type": "CosLR",
        "kwargs": {
            "epochs": 300,
            "initial_epochs": 10
        }
    },
    "dataset": {
        "train": {
            "_base_": {
                "NAME": "ShapeNet",
                "DATA_PATH": "./Point-MAE/data/ShapeNet55-34/ShapeNet-55",
                "N_POINTS": 8192,
                "PC_PATH": "./Point-MAE/data/ShapeNet55-34/shapenet_pc"
            },
            "others": {
                "subset": "train",
                "npoints": 1024,
                "bs": 256
            }
        },
        "val": {
            "_base_": {
                "NAME": "ShapeNet",
                "DATA_PATH": "./Point-MAE/data/ShapeNet55-34/ShapeNet-55",
                "N_POINTS": 8192,
                "PC_PATH": "./Point-MAE/data/ShapeNet55-34/shapenet_pc"
            },
            "others": {
                "subset": "test",
                "npoints": 1024,
                "bs": 256
            }
        },
        "extra_train_svm": {
            "_base_": {
                "NAME": "ModelNet",
                "DATA_PATH": "./Point-MAE/data/ModelNet/modelnet40_normal_resampled",
                "N_POINTS": 8192,
                "NUM_CATEGORY": 40,
                "USE_NORMALS": false
            },
            "others": {
                "subset": "train",
                "npoints": 1024
            }
        },
        "extra_test_svm": {
            "_base_": {
                "NAME": "ModelNet",
                "DATA_PATH": "./Point-MAE/data/ModelNet/modelnet40_normal_resampled",
                "N_POINTS": 8192,
                "NUM_CATEGORY": 40,
                "USE_NORMALS": false
            },
            "others": {
                "subset": "test",
                "npoints": 1024
            }
        },
        "test": {
            "_base_": {
                "NAME": "ShapeNet",
                "DATA_PATH": "./Point-MAE/data/ShapeNet55-34/ShapeNet-55",
                "N_POINTS": 8192,
                "PC_PATH": "./Point-MAE/data/ShapeNet55-34/shapenet_pc"
            },
            "others": {
                "subset": "test",
                "npoints": 1024,
                "bs": 256
            }
        }
    },
    "model": {
        "NAME": "Point_MAE",
        "group_size": 32,
        "num_group": 64,
        "loss": "cdl2",
        "transformer_config": {
            "mask_ratio": 0,
            "mask_type": "rand",
            "trans_dim": 384,
            "encoder_dims": 384,
            "depth": 12,
            "drop_path_rate": 0.1,
            "num_heads": 6,
            "decoder_depth": 4,
            "decoder_num_heads": 6
        }
    },
    "npoints": 1024,
    "total_bs": 256,
    "step_per_update": 1,
    "max_epoch": 300
}
